### ISSUE TITLE
Call to undefined executeSearchRequest()

### ISSUE THREAD

**Issue by onlinesid** [zingimmick/laravel-scout-opensearch#43]
I'm getting this error when using this scout driver:

```
Call to undefined method Zing\\LaravelScout\\OpenSearch\\Engines\\OpenSearchEngine::executeSearchRequest() at /var/task/vendor/babenkoivan/elastic-scout-driver-plus/src/Builders/SearchRequestBuilder.php:343)
```

**Comment by zingimmick** [comment]
`babenkoivan/elastic-scout-driver-plus` is not compatible with other Scout drivers, because it has a different interface. 
Ref: https://github.com/babenkoivan/elastic-scout-driver-plus/issues/115#issuecomment-1031200545

**Comment by onlinesid** [comment]
Thank you for that, that is the problem here (sigh)
