### ISSUE TITLE
Support laravel/scout v10

### ISSUE THREAD

**Issue by PaulMcITS** [zingimmick/laravel-scout-opensearch#49]
Fails to install with

Problem 1
    - zing/laravel-scout-opensearch[0.0.1, ..., 0.1.0, 1.0.0, ..., 1.3.0] require laravel/scout ^8.0 || ^9.1 -> found laravel/scout[v8.0.0, ..., v8.6.1, v9.1.0, ..., v9.8.1] but it conflicts with your root composer.json require (^10.0).
    - zing/laravel-scout-opensearch[2.0.0, ..., 2.1.0] require laravel/scout ^8.5 || ^9.1 -> found laravel/scout[v8.5.0, ..., v8.6.1, v9.1.0, ..., v9.8.1] but it conflicts with your root composer.json require (^10.0).
    - Root composer.json requires zing/laravel-scout-opensearch * -> satisfiable by zing/laravel-scout-opensearch[0.0.1, 0.1.0, 1.0.0, ..., 1.3.0, 2.0.0, 2.1.0].

**Comment by zingimmick** [comment]
Thanks for reporting, `laravel/scout` 10 has just been allowed in version `2.2.0`.
