### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by latheesan-k** [zingimmick/laravel-scout-opensearch#61]
I've installed and configured the package and when ever I try to index a record, I keep getting this error:

```
OpenSearch \ Common \ Exceptions \ NoNodesAvailableException
No alive nodes found in your cluster
``` 

My OpenSearch cluster is online in AWS and I checked via the `_dashboards` and I am able to create/retrieve records via the dev tool fine. I am just not able to access it via this package. 

I tried all of the following combination for the "host" and none of them work
* search-myapp-aaabbbcccdddeee.us-east-1.es.amazonaws.com
* search-myapp-aaabbbcccdddeee.us-east-1.es.amazonaws.com:443
* https://search-myapp-aaabbbcccdddeee.us-east-1.es.amazonaws.com
* https://search-myapp-aaabbbcccdddeee.us-east-1.es.amazonaws.com:9200

I've tested it in postman and it works fine
![image](https://github.com/zingimmick/laravel-scout-opensearch/assets/6196415/2fb7eedf-3d70-45dd-9471-72186142b0db)

Any ideas?

PHP 8.2.1
Laravel 10.4.1

**Comment by zingimmick** [comment]
Please check if you have configured SigV4 signing according to the steps in the documentation.
[Connecting to Amazon OpenSearch Service](https://opensearch.org/docs/latest/clients/php/#connecting-to-amazon-opensearch-service)

**Comment by zingimmick** [comment]
SigV4 signing configuration

```php
'sigV4Region' => 'us-east-1',
'sigV4Service' => 'es',
'sigV4CredentialProvider' => true, // Default credential provider.
// Using a custom access key and secret
// 'sigV4CredentialProvider' => [
//     'key' => 'awskeyid',
//     'secret' => 'awssecretkey',
// ]
```

If you want to log all failing requests and responses, please set a PSR-3 logger to use for the client.

```php
'logger' => (new Logger('opensearch'))->pushHandler(new RotatingFileHandler('opensearch')),
```

**Comment by latheesan-k** [comment]
Thanks, after configuring the SigV4 signing in the `config/scout.php` for `opensearch`, I tried to index a record again and now I am getting a different error message:

```
Aws \ Exception \ CredentialsException

Error retrieving credentials from the instance profile metadata service. (cURL error 28: 
Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 
for http://169.254.169.254/latest/meta-data/iam/security-credentials/)
```

I am little confused by this, because I did opt-in for a `Default credential provider` when I created the cluster initially. 

Here's the security configuration for my opensearch domain cluster:
![image](https://github.com/zingimmick/laravel-scout-opensearch/assets/6196415/8c897b15-b522-4410-bb24-9f2a447fe0e6)

**Comment by zingimmick** [comment]
> I did opt-in for a `Default credential provider` when I created the cluster initially.

How did you set up the credentials? [Use credentials from environment variables](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_environment.html) or [Shared config and credentials files](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_index.html#shared-files).

**Comment by latheesan-k** [comment]
I believe I have this solved now. I was under the impression iAM user key/secrets weren't required because the domain was created with internal user database (username/password) and assumed that was enough.

I've fixed it doing the following:
* Create a new iAM user and attach the OpenSearch policies (as required)
* Create access key/secret for the new iAM user
* Re-create the opensearch domain and `Set IAM ARN as master user` to the newly created iAM user's ARN
* Then configure the scout config like this:

```
    'opensearch' => [
        'hosts' => [env('OPENSEARCH_HOST', 'localhost:9200')],
        'basicAuthentication' => [env('OPENSEARCH_USER', 'admin'), env('OPENSEARCH_PASS', 'admin')],
        'retries' => env('OPENSEARCH_RETRYS', 2),
        'sigV4Region' => env('OPENSEARCH_REGION', 'us-east-1') ,
        'sigV4Service' => 'es',
        'sigV4CredentialProvider' => [
            'key' => env('OPENSEARCH_IAM_KEY'),
            'secret' => env('OPENSEARCH_IAM_SECRET'),
        ],
    ],
```

Now i am able to index the records.
